/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "on-surface": "#1a1c1d",
        "on-primary-container": "#848484",
        "surface-container-low": "#f3f3f4",
        "background": "#f9f9fa",
        "secondary-fixed-dim": "#c6c5cf",
        "surface-dim": "#dadadb",
        "on-tertiary-fixed-variant": "#474747",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#474747",
        "surface-container-highest": "#e2e2e3",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#e2e2e2",
        "surface-container": "#eeeeef",
        "outline-variant": "#cfc4c5",
        "on-tertiary-container": "#848484",
        "surface-container-high": "#e8e8e9",
        "secondary": "#5d5e66",
        "primary-fixed": "#e2e2e2",
        "surface-variant": "#e2e2e3",
        "surface": "#f9f9fa",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#46464e",
        "surface-tint": "#5e5e5e",
        "primary-container": "#1b1b1b",
        "inverse-surface": "#2f3132",
        "secondary-fixed": "#e3e1ec",
        "on-secondary-fixed": "#1a1b22",
        "inverse-on-surface": "#f0f1f2",
        "secondary-container": "#e3e1ec",
        "inverse-primary": "#c6c6c6",
        "on-tertiary": "#ffffff",
        "outline": "#7e7576",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#c6c6c6",
        "tertiary": "#000000",
        "on-tertiary-fixed": "#1b1b1b",
        "on-background": "#1a1c1d",
        "on-secondary-container": "#63646c",
        "on-surface-variant": "#4c4546",
        "tertiary-fixed-dim": "#c6c6c6",
        "primary": "#000000",
        "on-primary-fixed": "#1b1b1b",
        "tertiary-container": "#1b1b1b",
        "surface-bright": "#f9f9fa"
      },
      "spacing": {
        "xl": "40px",
        "xs": "4px",
        "md": "16px",
        "unit": "4px",
        "margin-desktop": "64px",
        "lg": "24px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "sm": "8px"
      },
      "fontFamily": {
        "headline-md": ["Outfit"],
        "headline-lg": ["Outfit"],
        "label-sm": ["Outfit"],
        "body-md": ["Outfit"],
        "headline-lg-mobile": ["Outfit"],
        "label-md": ["Outfit"],
        "display-lg": ["Outfit"],
        "body-lg": ["Outfit"]
      },
      "fontSize": {
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.03em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
